apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: quickstart-cp4i
spec:
  license:
    accept: true
    license: L-RJON-BUVMQX
    use: NonProduction
  queueManager:
    name: QUICKSTART
    mqsc:
      - configMap:
          items:
            - idp.mqsc
          name: idp-qm-mqsc
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      queueManager:
        type: ephemeral
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.2.0.1-r1-eus
  web:
    enabled: false