apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: mq-consumer
  namespace: CHANGEME # ClusterName from user input. Remember clusterName is mapped to a unique NS on the managed cluster.
spec:
  enableMetrics: false
  license:
    accept: true
    license: L-APEH-CJUCNR
    use: CloudPakForIntegrationProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 368Mi
          requests:
            cpu: 300m
            memory: 368Mi
  adminServerSecure: true
  router:
    timeout: 120s
  designerFlowsOperationMode: disabled
  createDashboardUsers: false
  service:
    endpointType: http
  version: '12.0'
  replicas: 1
  barURL: CHANGEME # GitRepo and FileName location from User Input
  configurations:
    - ace-app-config # Remember, this is hardcoded for the time being.