apiVersion: v1
metadata:
  name: CHANGEME-UserInput
baseDomain: CHANGEME-ConfigMap
controlPlane:
  architecture: CHANGME-ConfigMap
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      zones:
      - CHANGEME-ConfigMap-f(userinput-region)
      - CHANGEME-ConfigMap-f(userinput-region)
      - CHANGEME-ConfigMap-f(userinput-region)
      rootVolume:
        iops: CHANGEME-Configmap-f(userinput-size)
        size: CHANGME-Configmap-f(userinput-size)
        type: CHANGME-Configmap-f(userinput-size)
      type: CHANGME-Configmap-f(userinput-size)
compute:
- hyperthreading: Enabled
  architecture: CHANGEME-ConfigMap
  name: 'worker'
  replicas: 3
  platform:
    aws:
      rootVolume:
        iops: CHANGEME-Configmap-f(userinput-size)
        size: CHANGEME-Configmap-f(userinput-size)
        type: CHANGEME-Configmap-f(userinput-size)
      type: CHANGEME-Configmap-f(userinput-size)
      zones:
      - CHANGEME-ConfigMap-f(userinput-region)
      - CHANGEME-ConfigMap-f(userinput-region)
      - CHANGEME-ConfigMap-f(userinput-region)
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
  - cidr: CHANGEME-ConfigMap
    hostPrefix: 23
  machineNetwork:
  - cidr: CHANGEME-ConfigMap
  serviceNetwork:
  - CHANGEME-ConfigMap
platform:
  aws:
    region: CHANGEME-UserInput
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
    CHANGME-SECRET-PUBLICKEY-COMPONENT