apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mysql-aws-composition
  labels:
    crossplane.io/xrd: xpostgres.apac.catalyst.project.idp
    provider: aws
    type: production
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: apac.catalyst.project.idp/v1alpha1
    kind: xpostgresql
  resources:
  - name: aws-rds-postgres
    base:
      apiVersion: database.aws.crossplane.io/v1beta1
      kind: RDSInstance
      spec:
        forProvider:
          engine: mysql
          engineVersion: 8.0.28
          licenseModel: general-public-license
          masterUsername: admin
          multiAZ: false
          port: 3306
          skipFinalSnapshotBeforeDeletion: true
          publiclyAccessible: true
          storageEncrypted: false
          storageType: gp2
          enablePerformanceInsights: false
          enableIAMDatabaseAuthentication: false
          deletionProtection: false
          copyTagsToSnapshot: false
          backupRetentionPeriod: 0
          autoMinorVersionUpgrade: true
          allocatedStorage: 20
        providerConfigRef:
          name: aws-provider-config
        writeConnectionSecretToRef:
          name: default
          namespace: crossplane-system
    namespace: crossplane-system
    patches:
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
        - type: string
          string:
            fmt: "%s-postgresql"
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.parameters.region"
      toFieldPath: "spec.forProvider.region"
      transforms:
        - type: map
          map:
            us-east-2: Ohio
            us-east-1: N. Virginia
            us-west-1: N. California
            us-west-2: Oregon
            af-south-1: Cape Town
            ap-east-1: Hong Kong
            ap-northeast-1: Tokyo
            ap-northeast-2: Seoul
            ap-northeast-3: Osaka
            ap-southeast-1: Singapore
            ap-southeast-2: Sydney
            ap-southeast-3: Jakarta
            ap-south-1: Mumbai
            ap-south-2: Hyderabad
            ca-central-1: Central
            eu-central-1: Frankfurt
            eu-central-2: Zurich
            eu-west-1: Ireland
            eu-west-2: London
            eu-west-3: Paris
            eu-south-1: Milan
            eu-south-2: Spain
            eu-north-1: Stockholm
            me-central-1: UAE
            me-south-1: Bahrain
            sa-east-1: Sao Paulo
            us-gov-east-1: US-East
            us-gov-west-1: US-West
    - type: FromCompositeFieldPath
      fromFieldPath: "spec.parameters.class"
      toFieldPath: "spec.forProvider.dbInstanceClass"
      transforms:
        - type: map
          map:
            db.t3.small: small    # 2vCPU 2GiB
            db.t3.medium: medium  # 2vCPU 4GiB
            db.t3.large: large    # 2vCPU 8GiB
            db.t3.xlarge: xlarge  # 4vCPU 16GiB
    connectionDetails:
      - fromConnectionSecretKey: username
      - fromConnectionSecretKey: password
      - fromConnectionSecretKey: endpoint
      - fromConnectionSecretKey: port