apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  serviceAccountName: configure-provider-deployment-sa
  serviceAccount: configure-provider-deployment-sa
  containers:
  - name: ubuntu
    image: quay.io/marwan_attar_ibm/test_image
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
