apiVersion: v1
metadata:
  name: CHANGEME-UserInput
baseDomain: CHANGEME-ConfigMap
controlPlane:
  architecture: CHANGME-ConfigMap
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    aws:
      zones:
        - ap-southeast-2a
        - ap-southeast-2b
        - ap-southeast-2c
      rootVolume:
        iops: CHANGEME-Configmap-f(userinput-size)
        size: CHANGME-Configmap-f(userinput-size)
        type: CHANGME-Configmap-f(userinput-size)
      type: CHANGME-Configmap-f(userinput-size)
compute:
- hyperthreading: Enabled
  architecture: CHANGEME-ConfigMap
  name: 'worker'
  replicas: 3
  platform:
    aws:
      rootVolume:
        iops: CHANGEME-Configmap-f(userinput-size)
        size: CHANGEME-Configmap-f(userinput-size)
        type: CHANGEME-Configmap-f(userinput-size)
      type: CHANGEME-Configmap-f(userinput-size)
      zones:
        - ap-southeast-2a
        - ap-southeast-2b
        - ap-southeast-2c
networking:
  networkType: OpenShiftSDN
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: CHANGEME-UserInput
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
    CHANGME-SECRET-PUBLICKEY-COMPONENT