apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: CHANGEME-clusterName-pull-secret
  namespace: CHANGEME
spec: 
  data:
  - secretKey: CHANGEME-openshiftPullSecret
    remoteRef: 
      key: CHANGEME 
  refreshInterval: 24h0m0s
  secretStoreRef: 
    name: CHANGME-cluster
    kind: ClusterSecretStore
  target:
    name: CHANGEME-clusterName-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |-
          {{ .openshiftPullSecret | toString }}