apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: CHANGME-clusterName-aws-creds
  namespace: CHANGME-clusterName
spec:
  data:
    - secretKey: CHANGME-awsAccessKey
      remoteRef:
        key: CHANGEME
    - secretKey: CHANGEME-awsSecretKey
      remoteRef:
        key: CHANGEME
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: CHANGEME
    kind: ClusterSecretStore
  target:
    name: CHANGEME-clusterName-aws-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        aws_access_key_id: |-
          {{ .awsAccessKey | toString }}
        aws_secret_access_key: |-
          {{ .awsSecretKey | toString }}