apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: CHANGEME-clusterName-ssh-private-key
  namespace: CHANGEME-clusterName
spec:
  data:
  - secretKey: CHANGEME-openshiftSSHPrivateKey
    remoteRef: 
      key: CHANGEME
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: CHANGEME
    kind: ClusterSecretStore
  target:
    name: CHANGEME-ssh-private-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ssh-privatekey: |-
          {{ .openshiftSSHPrivateKey | toString }}
  