apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-provider-deployment-crb
subjects:
- kind: ServiceAccount
  name: CHANGEME
  namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: aws-provider-role
  apiGroup: rbac.authorization.k8s.io